
POST http://localhost:3003/api/blogs
Content-Type: application/json
Authorization: Bearer 

{
    "title": "Huippu Blogi",
    "author": "Kalle",
    "url": "https://klusteri.network",
    "likes": "42"
}