
PUT http://localhost:3003/api/blogs/6718fcfcad36c503a5db10bb
Content-Type: application/json

{
    "title": "Pöhinäkerroin",
    "author": "Leppätalokomitea",
    "url": "http://www.wikipedia.org",
    "likes": "42"
}