
POST http://localhost:3003/api/blogs
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImthbGxlIiwiaWQiOiI2N2ExY2FjMzMzMjllNzMwYTIyZmQ5NWMiLCJpYXQiOjE3Mzg2ODA0MDB9.OfXwCgTuhC45ByLR-YQ3BHyV8RnM5vDWndoELLRY4Yw

{
    "title": "Huippu Blogi",
    "author": "Kallen frendi",
    "url": "https://klusteri.network",
    "likes": "42"
}